[[parser]]
name = "cpp"
repository = "https://github.com/tree-sitter/tree-sitter-cpp"
revision = "f41e1a044c8a84ea9fa8577fdd2eab92ec96de02"

[[parser]]
name = "css"
repository = "https://github.com/tree-sitter/tree-sitter-css"
revision = "c0d581e32d183a536731ed6c3a72758b27e20411"

[[parser]]
name = "go"
repository = "https://github.com/tree-sitter/tree-sitter-go"
revision = "3c3775faa968158a8b4ac190a7fda867fd5fb748"

[[parser]]
name = "html"
repository = "https://github.com/tree-sitter/tree-sitter-html"
revision = "5a5ca8551a179998360b4a4ca2c0f366a35acc03"

[[parser]]
name = "java"
repository = "https://github.com/tree-sitter/tree-sitter-java"
revision = "94703d5a6bed02b98e438d7cad1136c01a60ba2c"

[[parser]]
name = "javascript"
repository = "https://github.com/tree-sitter/tree-sitter-javascript"
revision = "3a837b6f3658ca3618f2022f8707e29739c91364"

[[parser]]
name = "json"
repository = "https://github.com/tree-sitter/tree-sitter-json"
revision = "ee35a6ebefcef0c5c416c0d1ccec7370cfca5a24"

[[parser]]
name = "php"
path = "php"
repository = "https://github.com/tree-sitter/tree-sitter-php"
revision = "f7cf7348737d8cff1b13407a0bfedce02ee7b046"

[[parser]]
name = "python"
repository = "https://github.com/tree-sitter/tree-sitter-python"
revision = "bffb65a8cfe4e46290331dfef0dbf0ef3679de11"

[[parser]]
name = "rust"
repository = "https://github.com/tree-sitter/tree-sitter-rust"
revision = "cad8a206f2e4194676b9699f26f6560d07130d3f"
