export type Language =
  | 'ada'
  | 'agda'
  | 'apex'
  | 'arduino'
  | 'asm'
  | 'astro'
  | 'authzed'
  | 'awk'
  | 'bash'
  | 'beancount'
  | 'bicep'
  | 'bibtex'
  | 'bitbake'
  | 'brightscript'
  | 'c'
  | 'c-sharp'
  | 'caddy'
  | 'cairo'
  | 'capnp'
  | 'cel'
  | 'chatito'
  | 'clojure'
  | 'cmake'
  | 'comment'
  | 'commonlisp'
  | 'cooklang'
  | 'cpon'
  | 'cpp'
  | 'css'
  | 'csv'
  | 'cuda'
  | 'cue'
  | 'cyberchef'
  | 'd'
  | 'dart'
  | 'devicetree'
  | 'dhall'
  | 'diff'
  | 'dockerfile'
  | 'dot'
  | 'editorconfig'
  | 'eex'
  | 'elixir'
  | 'elm'
  | 'embedded-template'
  | 'erlang'
  | 'fennel'
  | 'firrtl'
  | 'fish'
  | 'fortran'
  | 'fsharp'
  | 'func'
  | 'gdscript'
  | 'gitattributes'
  | 'gleam'
  | 'glsl'
  | 'gn'
  | 'go'
  | 'go-sum'
  | 'gomod'
  | 'gowork'
  | 'gpg-config'
  | 'graphql'
  | 'groovy'
  | 'gstlaunch'
  | 'hare'
  | 'haskell'
  | 'hcl'
  | 'heex'
  | 'hlsl'
  | 'html'
  | 'http'
  | 'hurl'
  | 'hyprlang'
  | 'ini'
  | 'ispc'
  | 'java'
  | 'javascript'
  | 'jinja'
  | 'jinja-inline'
  | 'jq'
  | 'jsdoc'
  | 'json'
  | 'json5'
  | 'jsonnet'
  | 'julia'
  | 'just'
  | 'kconfig'
  | 'kdl'
  | 'kotlin'
  | 'lean'
  | 'linkerscript'
  | 'liquid'
  | 'llvm'
  | 'lua'
  | 'luadoc'
  | 'luap'
  | 'luau'
  | 'make'
  | 'markdown'
  | 'matlab'
  | 'mermaid'
  | 'meson'
  | 'move'
  | 'nginx'
  | 'nim'
  | 'nix'
  | 'nqc'
  | 'nu'
  | 'objc'
  | 'ocaml'
  | 'odin'
  | 'pem'
  | 'php'
  | 'pkl'
  | 'po'
  | 'poe-filter'
  | 'pony'
  | 'powershell'
  | 'printf'
  | 'prisma'
  | 'promql'
  | 'properties'
  | 'proto'
  | 'psv'
  | 'pug'
  | 'puppet'
  | 'purescript'
  | 'pymanifest'
  | 'python'
  | 'ql'
  | 'ql-dbscheme'
  | 'qmljs'
  | 'query'
  | 'r'
  | 'racket'
  | 're2c'
  | 'readline'
  | 'regex'
  | 'rego'
  | 'requirements'
  | 'rescript'
  | 'ron'
  | 'ruby'
  | 'rust'
  | 'scala'
  | 'scss'
  | 'slang'
  | 'smali'
  | 'solidity'
  | 'squirrel'
  | 'svelte'
  | 'systemverilog'
  | 'tablegen'
  | 'terraform'
  | 'thrift'
  | 'tsv'
  | 'typescript'
  | 'typst'
  | 'udev'
  | 'ungrammar'
  | 'uxntal'
  | 'vala'
  | 'verilog'
  | 'vim'
  | 'wgsl'
  | 'wgsl-bevy'
  | 'xcompose'
  | 'yaml'
  | 'toml'
  | 'xml'
  | 'sql'
  | 'ssh-config'
  | 'starlark'
  | 'tcl'
  | 'tsx'
  | 'zig'
  | 'zsh';

export interface LanguageConfig {
  name: Language;
  displayName: string;
  wasmPath: string;
  highlightQueryPath: string;
  sampleCode: string;
}

export interface ParserMetadata {
  repository: string;
  revision: string;
  sourcePath?: string;
}

export interface SyntaxNode {
  id?: number;
  typeId: number;
  grammarId: number;
  grammarType: string;
  type: string;
  text: string;
  isNamed: boolean;
  isExtra: boolean;
  isError: boolean;
  isMissing: boolean;
  hasError: boolean;
  hasChanges: boolean;
  startIndex: number;
  endIndex: number;
  startPosition: { row: number; column: number };
  endPosition: { row: number; column: number };
  parseState: number;
  nextParseState: number;
  childCount: number;
  namedChildCount: number;
  descendantCount: number;
  parent: SyntaxNode | null;
  children: SyntaxNode[];
  child: (index: number) => SyntaxNode | null;
  equals: (other: SyntaxNode) => boolean;
  fieldNameForChild: (index: number) => string | null;
}

export interface SyntaxRange {
  from: number;
  to: number;
}

export interface QueryCapture {
  name: string;
  node: SyntaxNode;
  range: SyntaxRange;
}
