name: Update Parsers

on:
  schedule:
  - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: update-parsers
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  parsers:
    outputs:
      batches: ${{ steps.parsers.outputs.batches }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: List Parser Batches
      id: parsers
      run: |
        parser_batches=$(jq -c -f .github/scripts/parser-batches.jq manifest.json)
        echo "batches=$parser_batches" >> "$GITHUB_OUTPUT"

  update:
    name: Update Parser Batch ${{ strategy.job-index }}
    needs: parsers
    if: needs.parsers.outputs.batches != '[]'

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        batch: ${{ fromJson(needs.parsers.outputs.batches) }}

    uses: ./.github/workflows/update-parser-batch.yaml
    with:
      parsers: ${{ matrix.batch }}
    secrets: inherit
